openapi: 3.0.1
info:
  title: RESTful-Calculator
  description: Calculator API
  version: '0.1'
servers:
  - url: 'http://localhost:8080'
paths:
  /api/calculator/divide:
    get:
      description: 'Returns a result, based on the values entered. or non numeric , negative numbers will simulate API error conditions'
      parameters:
        - name: firstValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '150'
        - name: secondValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '2'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
        '400':
          description: Please enter a valid input
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:8080'
    servers:
      - url: 'http://localhost:8080'
  /api/calculator/multiply:
    get:
      description: 'Returns a result, based on the values entered. or non numeric , negative numbers will simulate API error conditions'
      parameters:
        - name: firstValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '150'
        - name: secondValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '5'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
        '400':
          description: Please enter a valid input
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:8080'
    servers:
      - url: 'http://localhost:8080'
  /api/calculator/subtract:
    get:
      description: 'Returns a result, based on the values entered. or non numeric , negative numbers will simulate API error conditions'
      parameters:
        - name: firstValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '150'
        - name: secondValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '5'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
        '400':
          description: Please enter a valid input
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:8080'
    servers:
      - url: 'http://localhost:8080'
  /api/calculator/add:
    get:
      description: 'Returns a result, based on the values entered. or non numeric , negative numbers will simulate API error conditions'
      parameters:
        - name: firstValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '150'
        - name: secondValue
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
          example: '1250'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
        '400':
          description: Please enter a valid input
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:8080'
    servers:
      - url: 'http://localhost:8080'
   /api/calculator/fibbonachi/8:
    get:
      description: 'Returns a Fibonacci sequence up to the number entered. or non numeric , negative numbers will simulate API error conditions'
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
        '400':
          description: Please enter a valid input
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://localhost:8080'
    servers:
      - url: 'http://localhost:8080'
components: {}